# Generated by Django 6.0.6 on 2026-07-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_absence_historicalabsence_shifttraderequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["name"]},
        ),
    ]
