# Generated by Django 6.0.6 on 2026-07-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_alter_skill_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Optional. Nötig für den Jugendschutz (ArGV 5) bei Lernenden/Auszubildenden unter 18 Jahren -- ohne Angabe wird der Mitarbeiter als volljährig behandelt.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Optional. Nötig für den Jugendschutz (ArGV 5) bei Lernenden/Auszubildenden unter 18 Jahren -- ohne Angabe wird der Mitarbeiter als volljährig behandelt.",
                null=True,
            ),
        ),
    ]
