# Generated by Django 6.0.6 on 2026-07-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_employee_birth_date_historicalemployee_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="absence",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Offen"),
                    ("approved", "Genehmigt"),
                    ("rejected", "Abgelehnt"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalabsence",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Offen"),
                    ("approved", "Genehmigt"),
                    ("rejected", "Abgelehnt"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shifttraderequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Offen"),
                    (
                        "employee_accepted",
                        "Von Mitarbeiter angenommen, wartet auf Freigabe",
                    ),
                    ("accepted", "Angenommen"),
                    ("declined", "Abgelehnt"),
                    ("cancelled", "Zurückgezogen"),
                    ("rejected", "Von Planer abgelehnt"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
