# Generated by Django 6.0.6 on 2026-07-24 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tenant_time_record_deviation_tolerance_minutes"),
        ("scheduling", "0006_historicaltimerecord_timerecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltimerecord",
            name="actual_break_minutes",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Nur relevant ohne Segmente -- bei Segmenten ergibt sich die Pause aus den Lücken.",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltimerecord",
            name="actual_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltimerecord",
            name="actual_start",
            field=models.TimeField(
                blank=True,
                help_text="Nur relevant, wenn das Template keine Segmente hat (Block 1.12) -- sonst siehe TimeRecordSegment. Bei Nachtschichten über Mitternacht: Endzeit < Startzeit ist erlaubt.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="timerecord",
            name="actual_break_minutes",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Nur relevant ohne Segmente -- bei Segmenten ergibt sich die Pause aus den Lücken.",
            ),
        ),
        migrations.AlterField(
            model_name="timerecord",
            name="actual_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timerecord",
            name="actual_start",
            field=models.TimeField(
                blank=True,
                help_text="Nur relevant, wenn das Template keine Segmente hat (Block 1.12) -- sonst siehe TimeRecordSegment. Bei Nachtschichten über Mitternacht: Endzeit < Startzeit ist erlaubt.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TimeRecordSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("actual_start", models.TimeField()),
                ("actual_end", models.TimeField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
                (
                    "time_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="scheduling.timerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("time_record", "order")},
            },
        ),
        migrations.CreateModel(
            name="TimeTemplateSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                (
                    "end_time",
                    models.TimeField(
                        help_text="Segmente, die über Mitternacht gehen, werden aktuell nicht unterstützt (nur ein einzelnes Segment darf über Mitternacht hinausgehen)."
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="scheduling.timetemplate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("template", "order")},
            },
        ),
    ]
