# Generated by Django 6.0.6 on 2026-07-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0007_alter_historicaltimerecord_actual_break_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="maximum_weekly_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Überschreibt Tenant.maximum_weekly_hours (gesetzliche/GAV-Höchstgrenze, Art. 9 ArG) für diesen Mitarbeiter. Leer lassen, um den Tenant-Wert zu übernehmen.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="standard_weekly_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Überschreibt Tenant.standard_weekly_hours (Normalarbeitszeit/Soll für die Überzeitberechnung, Art. 13 ArG) für diesen Mitarbeiter. Leer lassen, um den Tenant-Wert zu übernehmen.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="maximum_weekly_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Überschreibt Tenant.maximum_weekly_hours (gesetzliche/GAV-Höchstgrenze, Art. 9 ArG) für diesen Mitarbeiter. Leer lassen, um den Tenant-Wert zu übernehmen.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="standard_weekly_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Überschreibt Tenant.standard_weekly_hours (Normalarbeitszeit/Soll für die Überzeitberechnung, Art. 13 ArG) für diesen Mitarbeiter. Leer lassen, um den Tenant-Wert zu übernehmen.",
                null=True,
            ),
        ),
    ]
