# Generated by Django 6.0.6 on 2026-07-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0008_employee_maximum_weekly_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="overtime_balance_carryover_hours",
            field=models.FloatField(
                default=0,
                help_text="Überstunden-Saldo beim Systemstart (z. B. aus der vorherigen Zeiterfassung übernommen). Wird zum seit der ersten erfassten Schicht berechneten Saldo addiert.",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="vacation_days_per_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Überschreibt Tenant.default_vacation_days_per_year (Ferienanspruch in Arbeitstagen) für diesen Mitarbeiter. Leer lassen, um den Tenant-Wert zu übernehmen.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="overtime_balance_carryover_hours",
            field=models.FloatField(
                default=0,
                help_text="Überstunden-Saldo beim Systemstart (z. B. aus der vorherigen Zeiterfassung übernommen). Wird zum seit der ersten erfassten Schicht berechneten Saldo addiert.",
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="vacation_days_per_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Überschreibt Tenant.default_vacation_days_per_year (Ferienanspruch in Arbeitstagen) für diesen Mitarbeiter. Leer lassen, um den Tenant-Wert zu übernehmen.",
                null=True,
            ),
        ),
    ]
