# Generated by Django 6.0.6 on 2026-08-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0010_shiftpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="last_night_work_medical_exam_date",
            field=models.DateField(
                blank=True,
                help_text="Datum der letzten arbeitsmedizinischen Untersuchung (Art. 17c ArG) -- Pflicht bei regelmässiger Nachtarbeit, alle 2 Jahre bzw. jährlich ab 45 Jahren (Art. 45 ArGV 1). Nur relevant, wenn night_work_summary() regelmässige Nachtarbeit erkennt.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="last_night_work_medical_exam_date",
            field=models.DateField(
                blank=True,
                help_text="Datum der letzten arbeitsmedizinischen Untersuchung (Art. 17c ArG) -- Pflicht bei regelmässiger Nachtarbeit, alle 2 Jahre bzw. jährlich ab 45 Jahren (Art. 45 ArGV 1). Nur relevant, wenn night_work_summary() regelmässige Nachtarbeit erkennt.",
                null=True,
            ),
        ),
    ]
