# Generated by Django 6.0.6 on 2026-08-05 11:13

import scheduling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0011_employee_last_night_work_medical_exam_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employment_start_date",
            field=models.DateField(
                default=scheduling.models._default_employment_start_date,
                help_text="Eintrittsdatum -- Startpunkt für das Jahressoll im Arbeitszeitmodell (annual_target_hours()/time_account_summary()): Wochen vor diesem Datum zählen weder als Soll noch als Ist, auch wenn sie im laufenden Kalenderjahr liegen (z. B. bei unterjährigem Eintritt).",
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="employment_start_date",
            field=models.DateField(
                default=scheduling.models._default_employment_start_date,
                help_text="Eintrittsdatum -- Startpunkt für das Jahressoll im Arbeitszeitmodell (annual_target_hours()/time_account_summary()): Wochen vor diesem Datum zählen weder als Soll noch als Ist, auch wenn sie im laufenden Kalenderjahr liegen (z. B. bei unterjährigem Eintritt).",
            ),
        ),
    ]
