# Generated by Django 6.0.6 on 2026-08-05 16:27
#
# Enthält zusätzlich zum generierten CreateModel eine RunPython-Datenmigration
# (README Punkt 17) -- die erste in diesem Projekt: für jede bestehende
# Employee.nodes-Zuordnung wird eine gleichwertige Employment-Zeile angelegt
# (pensum_pct = Employee.employment_pct), damit bereits gepflegte
# Stations-Zuordnungen (inkl. produktiver Praxisdaten) nicht manuell neu
# erfasst werden müssen. Rein additiv -- Employee.nodes selbst bleibt
# unangetastet, die Migration ist daher ohne Datenverlust reversibel.

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def backfill_employments_from_employee_nodes(apps, schema_editor):
    Employee = apps.get_model("scheduling", "Employee")
    Employment = apps.get_model("scheduling", "Employment")

    rows = []
    for employee in Employee.objects.all().prefetch_related("nodes"):
        for node in employee.nodes.all():
            rows.append(
                Employment(
                    tenant_id=employee.tenant_id,
                    employee_id=employee.id,
                    node_id=node.id,
                    pensum_pct=employee.employment_pct,
                    title="",
                    is_team_lead=False,
                )
            )
    if rows:
        Employment.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_tenant_canton_tenantholidayoverride"),
        ("scheduling", "0012_employee_employment_start_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pensum_pct",
                    models.PositiveSmallIntegerField(
                        help_text="Pensum in % für diese einzelne Anstellung, z. B. 60.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Rollenbezeichnung dieser Anstellung, z. B. 'Arzt'.",
                        max_length=100,
                    ),
                ),
                ("is_team_lead", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employments",
                        to="scheduling.employee",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employments",
                        to="scheduling.node",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["node__path"],
                "unique_together": {("employee", "node")},
            },
        ),
        migrations.RunPython(
            backfill_employments_from_employee_nodes, reverse_code=migrations.RunPython.noop
        ),
    ]
