# Generated by Django 6.0.6 on 2026-08-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0013_employment"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetemplate",
            name="minimum_staffing",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Mindestanzahl gleichzeitig eingeteilter Mitarbeitender an diesem Schichttyp; 0 = keine Mindestbesetzung definiert.",
            ),
        ),
    ]
