# Generated by Django 6.0.6 on 2026-08-06 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0014_timetemplate_minimum_staffing"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shiftassignment",
            unique_together={("employee", "date", "template")},
        ),
    ]
