# Generated by Django 6.0.6 on 2026-08-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0015_alter_shiftassignment_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetemplate",
            name="category",
            field=models.CharField(
                choices=[("shift", "Dienst"), ("special", "Spezialität")],
                default="shift",
                help_text="Nutzer-Feedback (2026-08): reine UI-Gruppierung für die Stempelleisten im Planblatt/Jahresplan -- eine eigene Zeile für Spezialitäten wie z. B. Pikettdienst, getrennt von den regulären Diensten. Keine Regel-Engine-Auswirkung.",
                max_length=20,
            ),
        ),
    ]
