# Generated by Django 6.0.6 on 2026-08-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0019_absence_type_fk_finish"),
    ]

    operations = [
        migrations.AddField(
            model_name="absencetype",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Kurzes Kürzel/Glyphe fürs Planblatt (z. B. 'F' oder ein Emoji), analog TimeTemplate.icon.",
                max_length=50,
            ),
        ),
    ]
