# Generated by Django 6.0.6 on 2026-08-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0020_absencetype_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="absence",
            name="day_portion",
            field=models.CharField(
                choices=[
                    ("full", "Ganzer Tag"),
                    ("morning", "Nur vormittags"),
                    ("afternoon", "Nur nachmittags"),
                ],
                default="full",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalabsence",
            name="day_portion",
            field=models.CharField(
                choices=[
                    ("full", "Ganzer Tag"),
                    ("morning", "Nur vormittags"),
                    ("afternoon", "Nur nachmittags"),
                ],
                default="full",
                max_length=20,
            ),
        ),
    ]
