# Generated by Django 6.0.6 on 2026-08-09 17:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_tenant_canton_tenantholidayoverride"),
        ("scheduling", "0021_absence_day_portion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPregnancy",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "expected_birth_date",
                    models.DateField(
                        help_text="Voraussichtlicher Geburtstermin, bei Bekanntgabe erfasst."
                    ),
                ),
                (
                    "actual_birth_date",
                    models.DateField(
                        blank=True,
                        help_text="Tatsächliches Geburtsdatum, sobald bekannt -- korrigiert die ab der Niederkunft gerechneten Schutzfristen (Art. 35a Abs. 3 ArG). Leer lassen, solange die Geburt noch aussteht; expected_birth_date wird bis dahin als Schätzung verwendet.",
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="scheduling.employee",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pregnancy",
                "verbose_name_plural": "historical pregnancys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Pregnancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_birth_date",
                    models.DateField(
                        help_text="Voraussichtlicher Geburtstermin, bei Bekanntgabe erfasst."
                    ),
                ),
                (
                    "actual_birth_date",
                    models.DateField(
                        blank=True,
                        help_text="Tatsächliches Geburtsdatum, sobald bekannt -- korrigiert die ab der Niederkunft gerechneten Schutzfristen (Art. 35a Abs. 3 ArG). Leer lassen, solange die Geburt noch aussteht; expected_birth_date wird bis dahin als Schätzung verwendet.",
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pregnancies",
                        to="scheduling.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-expected_birth_date"],
            },
        ),
    ]
