# Generated by Django 6.0.6 on 2026-08-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0022_historicalpregnancy_pregnancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetemplate",
            name="surcharge_pct",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Nutzer-Feedback (2026-08): 'Spezialitäten wie Pikett können auch zuschlagspflichtig sein'. Lohnzuschlag in % der geplanten Stunden dieses Schichttyps (0 = kein Zuschlag) -- wirkt nur bei Kategorie 'Spezialität' (siehe Employee.monthly_summary): reguläre Dienste laufen bereits über den Soll/Ist-Vergleich (Überzeit) sowie die zeitpunktbasierten Nacht-/Sonntagszuschläge, ein zusätzlicher Prozentsatz hier würde sich damit überschneiden. Erscheint pro Schichttyp einzeln aufgeschlüsselt in der Monatsauswertung (Block 2.6) -- bewusst nicht zu einer einzigen Summe zusammengefasst, da das spätere Lohnart-Mapping (Punkt 30) pro Spezialität einen eigenen Lohnart-Code braucht (z. B. 'Pikett Wochentag' und 'Pikett Wochenende' können in der Kundenlohnsoftware unterschiedliche Codes haben).",
            ),
        ),
    ]
