# Generated by Django 6.0.6 on 2026-08-11 07:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_tenant_flextime_corridor_hours"),
        ("scheduling", "0023_timetemplate_surcharge_pct"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalOvertimeSettlement",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "hours",
                    models.FloatField(
                        help_text="Bestätigte Stunden ausserhalb des Gleitzeit-Korridors."
                    ),
                ),
                (
                    "surcharge_hours",
                    models.FloatField(
                        help_text="hours * Tenant.overtime_surcharge_pct/100 zum Bestätigungszeitpunkt."
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="scheduling.employee",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical overtime settlement",
                "verbose_name_plural": "historical overtime settlements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OvertimeSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "hours",
                    models.FloatField(
                        help_text="Bestätigte Stunden ausserhalb des Gleitzeit-Korridors."
                    ),
                ),
                (
                    "surcharge_hours",
                    models.FloatField(
                        help_text="hours * Tenant.overtime_surcharge_pct/100 zum Bestätigungszeitpunkt."
                    ),
                ),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_settlements",
                        to="scheduling.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("employee", "year", "month")},
            },
        ),
    ]
