# Generated by Django 6.0.6 on 2026-08-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0024_historicalovertimesettlement_overtimesettlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="absencetype",
            name="counts_as_sick_leave",
            field=models.BooleanField(
                default=False,
                help_text="Genehmigte Tage dieses Typs zählen gegen den Lohnfortzahlungs-Anspruch bei Krankheit (Art. 324a OR, Employee.sick_pay_summary()).",
            ),
        ),
    ]
