# Generated by Django 6.0.6 on 2026-08-11 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_tenant_sick_pay_model_tenant_sick_pay_scale_and_more"),
        ("scheduling", "0025_absencetype_counts_as_sick_leave"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollCategoryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("regular_hours", "Normalstunden"),
                            ("overtime", "Überstunden"),
                            ("night_credit", "Nacht-Zeitgutschrift (regelmässig)"),
                            ("night_surcharge", "Nacht-Lohnzuschlag (gelegentlich)"),
                            ("sunday_surcharge", "Sonntagszuschlag"),
                            ("vacation_days", "Ferientage"),
                            ("sick_days", "Krankheitstage"),
                            ("other_absence_days", "Sonstige Absenztage"),
                            ("holidays", "Feiertage"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "payroll_code",
                    models.CharField(
                        help_text="Vom Kunden vergebener Lohnart-Code.", max_length=50
                    ),
                ),
                (
                    "payroll_label",
                    models.CharField(
                        blank=True,
                        help_text="Freitext, nur zur Anzeige.",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inaktive Zeilen werden beim Export ausgelassen (z. B. falls ein Kunde eine Kategorie bereits anders löst).",
                    ),
                ),
                (
                    "special_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nur gesetzt für eine Spezialität mit Zuschlag statt einer festen Kategorie oben -- genau eines von category/special_template muss gesetzt sein.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_mappings",
                        to="scheduling.timetemplate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("category__isnull", False),
                                ("special_template__isnull", True),
                            ),
                            models.Q(
                                ("category__isnull", True),
                                ("special_template__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="payrollcategorymapping_exactly_one_of_category_or_template",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("special_template__isnull", True)),
                        fields=("tenant", "category"),
                        name="unique_payroll_category_per_tenant",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("category__isnull", True)),
                        fields=("tenant", "special_template"),
                        name="unique_payroll_special_template_per_tenant",
                    ),
                ],
            },
        ),
    ]
