# Generated by Django 6.0.6 on 2026-08-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0026_payrollcategorymapping"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payrollcategorymapping",
            options={"ordering": ["id"]},
        ),
    ]
