# Generated by Django 6.0.6 on 2026-08-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0027_alter_payrollcategorymapping_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="cost_center",
            field=models.CharField(
                blank=True,
                help_text="Kostenstelle für den Lohn-Export (Block 2 Punkt 30/31). Leer lassen, um von der übergeordneten Station zu erben (siehe effective_cost_center()) -- ein Team ohne eigene Kostenstelle übernimmt so automatisch die seiner Station.",
                max_length=50,
            ),
        ),
    ]
