# Generated by Django 6.0.6 on 2026-08-11 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_tenant_sick_pay_model_tenant_sick_pay_scale_and_more"),
        ("scheduling", "0028_node_cost_center"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payrollcategorymapping",
            name="payrollcategorymapping_exactly_one_of_category_or_template",
        ),
        migrations.RemoveConstraint(
            model_name="payrollcategorymapping",
            name="unique_payroll_category_per_tenant",
        ),
        migrations.RemoveConstraint(
            model_name="payrollcategorymapping",
            name="unique_payroll_special_template_per_tenant",
        ),
        migrations.AddField(
            model_name="payrollcategorymapping",
            name="absence_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Nur gesetzt für eine Absenzart, die weder Ferien- noch Krankheits-Anspruch abzieht (z. B. Militärdienst, unbezahlter Urlaub) -- genau eines von category/special_template/absence_type muss gesetzt sein.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payroll_mappings",
                to="scheduling.absencetype",
            ),
        ),
        migrations.AlterField(
            model_name="payrollcategorymapping",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("regular_hours", "Normalstunden"),
                    ("overtime", "Überstunden"),
                    ("night_credit", "Nacht-Zeitgutschrift (regelmässig)"),
                    ("night_surcharge", "Nacht-Lohnzuschlag (gelegentlich)"),
                    ("sunday_surcharge", "Sonntagszuschlag"),
                    ("vacation_days", "Ferientage"),
                    ("sick_days", "Krankheitstage"),
                    ("sick_days_exhausted", "Krankheitstage (Anspruch erschöpft)"),
                    ("holidays", "Feiertage"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payrollcategorymapping",
            name="special_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Nur gesetzt für eine Spezialität mit Zuschlag statt einer festen Kategorie oben -- genau eines von category/special_template/absence_type muss gesetzt sein.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payroll_mappings",
                to="scheduling.timetemplate",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollcategorymapping",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("absence_type__isnull", True),
                        ("category__isnull", False),
                        ("special_template__isnull", True),
                    ),
                    models.Q(
                        ("absence_type__isnull", True),
                        ("category__isnull", True),
                        ("special_template__isnull", False),
                    ),
                    models.Q(
                        ("absence_type__isnull", False),
                        ("category__isnull", True),
                        ("special_template__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="payrollcategorymapping_exactly_one_of_category_or_template_or_absence_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollcategorymapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("absence_type__isnull", True), ("special_template__isnull", True)
                ),
                fields=("tenant", "category"),
                name="unique_payroll_category_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollcategorymapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("absence_type__isnull", True), ("category__isnull", True)
                ),
                fields=("tenant", "special_template"),
                name="unique_payroll_special_template_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollcategorymapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("category__isnull", True), ("special_template__isnull", True)
                ),
                fields=("tenant", "absence_type"),
                name="unique_payroll_absence_type_per_tenant",
            ),
        ),
    ]
