# Generated by Django 6.0.6 on 2026-08-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0029_payrollcategorymapping_absence_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="termination_date",
            field=models.DateField(
                blank=True,
                help_text="Austrittsdatum. Sobald dieses Datum erreicht ist, deaktiviert der management command deactivate_expired_employees automatisch is_active und -- falls vorhanden -- den Login-Zugang (user.is_active), siehe EmployeeViewSet.deactivate für die sofortige, manuelle Variante desselben Vorgangs.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="termination_date",
            field=models.DateField(
                blank=True,
                help_text="Austrittsdatum. Sobald dieses Datum erreicht ist, deaktiviert der management command deactivate_expired_employees automatisch is_active und -- falls vorhanden -- den Login-Zugang (user.is_active), siehe EmployeeViewSet.deactivate für die sofortige, manuelle Variante desselben Vorgangs.",
                null=True,
            ),
        ),
    ]
