# Generated by Django 6.0.6 on 2026-08-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_tenant_onboarding_completed"),
        ("scheduling", "0030_employee_termination_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="is_forest_root",
            field=models.BooleanField(
                default=False,
                help_text="Interner, für Endnutzer unsichtbarer Wurzelknoten -- genau einer pro Tenant (siehe get_or_create_forest_root()). Echte Stationen werden nie mehr direkt als treebeard-Wurzel angelegt, sondern immer als Kind dieses Knotens -- verhindert, dass alle Tenants sich einen einzigen, global geteilten Namensraum auf Wurzelebene teilen.",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_forest_root", True)),
                fields=("tenant",),
                name="unique_forest_root_per_tenant",
            ),
        ),
    ]
