# Generated by Django 6.0.6 on 2026-08-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0032_node_forest_root_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="fixed_weekdays_off",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Wochentage, die fest arbeitsfrei sind (0=Montag ... 6=Sonntag, wie date.weekday()). Für Teilzeit das individuelle Wochenmuster, für ein Team ohne Wochenend-Betrieb z. B. [5, 6] auch bei Vollzeitkräften. Leer = keine festen freien Tage (übliches Vollzeit-Muster, nur der gesetzliche Wochenruhetag gilt).",
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="fixed_weekdays_off",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Wochentage, die fest arbeitsfrei sind (0=Montag ... 6=Sonntag, wie date.weekday()). Für Teilzeit das individuelle Wochenmuster, für ein Team ohne Wochenend-Betrieb z. B. [5, 6] auch bei Vollzeitkräften. Leer = keine festen freien Tage (übliches Vollzeit-Muster, nur der gesetzliche Wochenruhetag gilt).",
            ),
        ),
    ]
