# Generated by Django 6.0.6 on 2026-08-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0033_employee_fixed_weekdays_off"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftpreference",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Offen"),
                    ("approved", "Freigegeben"),
                    ("rejected", "Abgelehnt"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
