# Generated by Django 6.0.6 on 2026-08-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0034_shiftpreference_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetemplate",
            name="fills_remaining_capacity",
            field=models.BooleanField(
                default=False,
                help_text="Auffülldienst: statt einer festen Mindestbesetzung erhalten alle an diesem Tag arbeitspflichtigen Mitarbeitenden dieses Teams, die keinen anderen regulären Dienst haben, automatisch diesen Schichttyp (z. B. 'Gleitzeit'). Höchstens ein Auffülldienst pro Team.",
            ),
        ),
    ]
