# Generated by Django 6.0.6 on 2026-07-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="maximum_daily_span_hours",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="Maximale Tagesspanne von Arbeitsbeginn bis Arbeitsende inkl. Pausen, in Stunden (Art. 10 Abs. 3 ArG).",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="maximum_weekly_hours",
            field=models.PositiveSmallIntegerField(
                default=45,
                help_text="Wöchentliche Höchstarbeitszeit in Stunden (Art. 9 ArG: 45h für Gesundheits- und Büropersonal, 50h für übrige Betriebe -- je nach Branche/GAV anpassen).",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="minimum_rest_hours",
            field=models.PositiveSmallIntegerField(
                default=11,
                help_text="Mindestruhezeit zwischen zwei Schichten in Stunden (Art. 15a ArG: 11h Minimum).",
            ),
        ),
    ]
