# Generated by Django 6.0.6 on 2026-07-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tenant_maximum_daily_span_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="time_record_deviation_tolerance_minutes",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Ab dieser Abweichung (in Minuten) zwischen geplanter und tatsächlicher Arbeitszeit verlangt die Ist-Zeiterfassung eine Begründung (scheduling.models.TimeRecord).",
            ),
        ),
    ]
