# Generated by Django 6.0.6 on 2026-07-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tenant_time_record_deviation_tolerance_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="overtime_surcharge_pct",
            field=models.PositiveSmallIntegerField(
                default=25,
                help_text="Zuschlag auf Überzeitstunden in Prozent (Art. 13 Abs. 1 ArG: i. d. R. 25%, GAV-abhängig anpassbar).",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="standard_weekly_hours",
            field=models.PositiveSmallIntegerField(
                default=42,
                help_text="Normalarbeitszeit eines 100%-Pensums pro Woche, in Stunden (z. B. 42h GAV-Vorgabe in vielen Spitälern) -- die Basis für den Soll/Ist-Vergleich bei der Überzeitberechnung (Art. 13 ArG). Nicht zu verwechseln mit maximum_weekly_hours, der gesetzlichen Höchstgrenze.",
            ),
        ),
    ]
