# Generated by Django 6.0.6 on 2026-07-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_tenant_overtime_surcharge_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="default_vacation_days_per_year",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Gesetzlicher Mindestanspruch: 20 Arbeitstage (4 Wochen, Art. 329a Abs. 1 OR) für Erwachsene, 25 Tage (5 Wochen) für unter 20-Jährige (Art. 329a Abs. 3 OR) -- als Tenant-Default hinterlegt, pro Mitarbeiter überschreibbar für abweichende Verträge.",
            ),
        ),
    ]
