# Generated by Django 6.0.6 on 2026-08-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_tenant_default_vacation_days_per_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="night_work_permit_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Von Admin bestätigt: die nötige behördliche Bewilligung für regelmässige Nachtarbeit (Art. 17 ArG) liegt vor, bzw. der Betrieb ist davon ausgenommen. Ohne Bestätigung erscheint ein Warnhinweis, sobald ein Mitarbeiter regelmässige Nachtarbeit leistet (siehe Employee.night_work_summary).",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="night_work_regular_threshold_nights",
            field=models.PositiveSmallIntegerField(
                default=25,
                help_text="Ab dieser Anzahl Nächte mit Nachtarbeit pro Kalenderjahr gilt Nachtarbeit als 'regelmässig' (ArGV 1 Art. 31) -- Voraussetzung für Zeitgutschrift, Bewilligungspflicht und arbeitsmedizinische Untersuchungspflicht (Art. 17c ArG).",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="night_work_surcharge_pct",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Zeitgutschrift auf Nachtstunden bei regelmässiger Nachtarbeit, in Prozent (Art. 17b Abs. 1 ArG: i. d. R. 10%, sofern nicht durch einen gleichwertigen Lohnzuschlag abgegolten).",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sunday_work_surcharge_pct",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text="Lohnzuschlag auf Sonntagsstunden in Prozent (Art. 19 Abs. 3 ArG i. V. m. Art. 46 ArGV 1: i. d. R. 50%; für Dauerbetriebe wie viele Gesundheitseinrichtungen können Ausnahmen gelten -- auf 0 setzen, falls nicht zutreffend).",
            ),
        ),
    ]
