# Generated by Django 6.0.6 on 2026-08-05 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_tenant_night_work_permit_confirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="canton",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AG", "Aargau"),
                    ("AI", "Appenzell Innerrhoden"),
                    ("AR", "Appenzell Ausserrhoden"),
                    ("BE", "Bern"),
                    ("BL", "Basel-Landschaft"),
                    ("BS", "Basel-Stadt"),
                    ("FR", "Freiburg"),
                    ("GE", "Genf"),
                    ("GL", "Glarus"),
                    ("GR", "Graubünden"),
                    ("JU", "Jura"),
                    ("LU", "Luzern"),
                    ("NE", "Neuenburg"),
                    ("NW", "Nidwalden"),
                    ("OW", "Obwalden"),
                    ("SG", "St. Gallen"),
                    ("SH", "Schaffhausen"),
                    ("SO", "Solothurn"),
                    ("SZ", "Schwyz"),
                    ("TG", "Thurgau"),
                    ("TI", "Tessin"),
                    ("UR", "Uri"),
                    ("VD", "Waadt"),
                    ("VS", "Wallis"),
                    ("ZG", "Zug"),
                    ("ZH", "Zürich"),
                ],
                help_text="Kanton für den kantonalen Feiertagskalender (holidays-Bibliothek). Leer = kein automatischer Feiertagsabzug im Arbeitszeitmodell.",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="TenantHolidayOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("add", "Zusätzlicher Feiertag"),
                            ("remove", "Kein Feiertag (Ausnahme vom Kantonskalender)"),
                        ],
                        default="add",
                        max_length=10,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holiday_overrides",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("tenant", "date")},
            },
        ),
    ]
