# Generated by Django 6.0.6 on 2026-08-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_tenant_canton_tenantholidayoverride"),
        ("scheduling", "0022_historicalpregnancy_pregnancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="scoped_nodes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Nur für Planer/HR: schränkt die Sichtbarkeit auf diese Stationen (inkl. Unterstationen) ein. Leer = keine Einschränkung.",
                related_name="scoped_memberships",
                to="scheduling.node",
            ),
        ),
    ]
