# Generated by Django 6.0.6 on 2026-08-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_membership_scoped_nodes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="flextime_corridor_hours",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Nutzer-Feedback (2026-08): 'bei uns gilt Gleitzeit, nur angeordnete Überstunden werden effektiv abgerechnet'. Gleitzeit-Bandbreite in Stunden: der laufende Gleitzeitsaldo (scheduling.models.Employee.time_account_summary) darf sich innerhalb dieses Korridors frei bewegen -- weder Zuschlag noch Auszahlung, ohne dass Planer pro Schicht etwas markieren müssen. Erst der Anteil, der über den Korridor hinausgeht, wird in der Monatsauswertung als abrechnungsrelevant vorgeschlagen und muss dort einmalig pro Monat bestätigt werden (scheduling.models.OvertimeSettlement), bevor er in overtime_surcharge_hours einfliesst.",
            ),
        ),
    ]
