# Generated by Django 6.0.6 on 2026-08-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_tenant_flextime_corridor_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="occasional_night_work_surcharge_pct",
            field=models.PositiveSmallIntegerField(
                default=25,
                help_text="Lohnzuschlag auf Nachtstunden bei GELEGENTLICHER Nachtarbeit (unterhalb der Regelmässigkeits-Schwelle oben), in Prozent (Art. 17b Abs. 2 ArG: i. d. R. 25%). Anders als night_work_surcharge_pct (Zeitgutschrift, Art. 17b Abs. 1) ist das Geld statt Zeit -- die App kennt keinen Stundenlohn und rechnet daher keinen CHF-Betrag aus, nur die anzuwendende Stundenzahl + diesen Prozentsatz (siehe Employee.night_work_summary).",
            ),
        ),
    ]
