# Generated by Django 6.0.6 on 2026-08-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_tenant_occasional_night_work_surcharge_pct"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Erzwingt einen Passwortwechsel beim nächsten Login -- gesetzt, wenn ein Admin dieses Konto mit einem Temp-Passwort angelegt hat (siehe MembershipCreateSerializer).",
            ),
        ),
    ]
