# Generated by Django 6.0.6 on 2026-08-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="sick_pay_model",
            field=models.CharField(
                choices=[
                    ("scale", "Gerichtliche Skala (Basel/Bern/Zürich)"),
                    ("daily_allowance_insurance", "Krankentaggeldversicherung"),
                ],
                default="scale",
                help_text="Viele Betriebe versichern die Lohnfortzahlungspflicht über eine Krankentaggeldversicherung (typischerweise 80% Lohn ab Wartefrist) statt sich auf die gerichtliche Skala zu verlassen -- die Police ersetzt dann die Skala komplett.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sick_pay_scale",
            field=models.CharField(
                choices=[
                    ("basel", "Basler Skala"),
                    ("bern", "Berner Skala"),
                    ("zuerich", "Zürcher Skala"),
                ],
                default="basel",
                help_text="Nur relevant, wenn sick_pay_model = 'scale'. Die hinterlegten Werte sind gängige Näherungswerte der jeweiligen Skala -- vor Produktivnutzung mit einer Rechts-/Treuhandstelle verifizieren, da sich die Gerichtspraxis unterscheiden kann.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sick_pay_waiting_days",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Nur relevant, wenn sick_pay_model = 'daily_allowance_insurance': Wartefrist in Tagen (aus der Police), bis das Taggeld einsetzt -- vorher zahlt der Betrieb selbst weiter.",
            ),
        ),
    ]
