# Generated by Django 6.0.6 on 2026-08-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_tenant_sick_pay_model_tenant_sick_pay_scale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="night_shift_bonus_points_per_hour",
            field=models.FloatField(
                default=0.5,
                help_text="Fairness-Punkte je Nachtstunde (Employee.fairness_summary()) -- rein interne Transparenz-/Planungsgrösse, kein Lohnbestandteil.",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sunday_shift_bonus_points_per_hour",
            field=models.FloatField(
                default=1.0,
                help_text="Fairness-Punkte je Sonntagsstunde (Employee.fairness_summary()) -- rein interne Transparenz-/Planungsgrösse, kein Lohnbestandteil.",
            ),
        ),
    ]
