# Generated by Django 6.0.6 on 2026-08-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_tenant_night_shift_bonus_points_per_hour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="onboarding_completed",
            field=models.BooleanField(
                default=True,
                help_text="False nur für frisch per Self-Signup angelegte Tenants (core.views.SignupView) -- steuert, ob das Frontend den Einrichtungsassistenten (OnboardingWizard.jsx) statt der normalen App zeigt. Über den Django-Admin oder Fixtures/Tests angelegte Tenants bleiben unverändert sofort nutzbar (default True).",
            ),
        ),
    ]
