# Generated by Django 6.0.6 on 2026-08-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_tenant_onboarding_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="stripe_customer_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tenant",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tenant",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("active", "Aktiv"),
                    ("trialing", "Testphase"),
                    ("past_due", "Zahlung überfällig"),
                    ("canceled", "Gekündigt"),
                    ("incomplete", "Zahlung ausstehend"),
                ],
                default="active",
                help_text="Spiegelt den Stripe-Subscription-Status (siehe core.billing.handle_webhook_event) -- ACTIVE ist der sichere Default für nicht per Self-Signup angelegte Tenants (Admin/Fixtures/Tests), analog onboarding_completed.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="trial_employee_limit",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Maximal erlaubte aktive Mitarbeitende WÄHREND subscription_status=TRIALING (verhindert Missbrauch der kostenlosen Phase). Nach Abschluss eines Abos (ACTIVE) gilt kein Limit mehr -- Abrechnung erfolgt pro aktivem Mitarbeitenden.",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="trial_ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Ende der Testphase (nur gesetzt für per Self-Signup angelegte Tenants, siehe core.onboarding.seed_demo_tenant). Leer = keine zeitliche Einschränkung.",
                null=True,
            ),
        ),
    ]
